[project]
name = "cau26"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Olivier Labayle", email = "olabayle@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyyaml>=6.0.3",
]

[project.scripts]
cau26 = "cau26:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
