FROM python:3.12-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /opt/reproducibility

COPY . /opt/reproducibility

RUN uv sync

ENTRYPOINT ["uv", "run", "my_reproducible_analysis.py"]

CMD ["--help"]